- name: Manage power state of the first device
  hosts: localhost
  vars_files: ./variables.yaml
  tasks:
  - name: Manage power state of the first device
    dellemc.openmanage.redfish_powerstate:
      validate_certs: false
      baseuri: "{{ dell.idrac.uri }}"
      username: "{{ dell.idrac.user }}"
      password: "{{ dell.idrac.password }}"
      reset_type: "GracefulShutdown"
        