---
- name: Playbook to install microk8s
  hosts: { { hosts_group } }
  become: true
  tasks:
    - name: Ansible snap install microk8s
      community.general.snap:
        name: microk8s
        classic: true
